### ISSUE TITLE
[Porto Alegre/RS] Taylor Souza

### ISSUE THREAD

**Issue by Tayouza** [backend-br/me-contrata#100]
## Nome completo

Taylor Canabarro de Souza

## Localidade

Porto Alegre / RS

## Apresentação

Olá Me chamo Taylor, estou cursando Análise e desenvolvimento de sistemas pela FADERGS desde o início de 2021, e além da faculdade faço curso e projetos pessoais para aprimorar minhas habilidades, sinto já estar preparado para as oportunidades que virão.

## Outras Informações

Análise e desenvolvimento de sistemas - FADERGS 3º semestre
Curso Frontend completo - DankiCode
Curso PHP Jedai - DankiCode
Curso PHP - HCode

## Especialidades

- PHP
- JavaScript
- HTML
- CSS
- Laravel
- React
- Docker
- Sass
- GIT

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/taylorcanabarro/

## Site

https://tayouza.netlify.app/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
