### ISSUE TITLE
[São Paulo/SP] Tatiane Souto

### ISSUE THREAD

**Issue by tatisouto** [backend-br/me-contrata#13]
## Nome completo

Tatiane Almeida de Souto

## Localidade

São Paulo - SP

## Apresentação

- 15 anos de experiência em ambientes web (full stack),  com as seguintes tecnologias: 
**C#, ASP.NET MVC, Web Api, JQuery, Json, HTML 5, AngularJS, Bootstrap e Javascript;** 
- Atuação em projeto de Migração de aplicações VB 6.0 para .NET;
- Experiência em controle de demandas, seguindo definições de cronogramas, participação 
 de negociação de prazos e escopo. 

## Outras Informações
- Pró-Ativa, facilidade para trabalhar em equipe e liderar;
- Disponibilidade para trabalho imediata;
- Disponível para viagens.
- Participação ativa em Comunidades de Tecnologia e Meetup´s;

## Especialidades

- Asp.Net MVC
- C#
- WebApi
- AngularJs
- Jquery
- JavaScript
- Ajax
- Json
- HTML 5
- CSS
- Sql Server
- Oracle

## Nível

- [ ] Estágio
- [ ] Júnior
- [ ] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/tatianesouto/

## Site

https://github.com/tatisouto

**Comment by tatisouto** [comment]
[CV-TatianeAlmeidadeSouto-V012018.docx](https://github.com/backend-br/me-contrata/files/1958763/CV-TatianeAlmeidadeSouto-V012018.docx)

**Comment by Paulogrupe** [comment]
Bom dia 

Estou trabalhando vagas de front-end e back-end e gostaria de saber do seu interesse em participar.
Envie-me um curriculum para pg@individual.io

Grato

Paulo Grupe
