### ISSUE TITLE
[Quixadá/CE] Rodrigo Machado dos Santos

### ISSUE THREAD

**Issue by RodMdS** [backend-br/me-contrata#16]
## Nome completo

Rodrigo Machado dos Santos

## Localidade

Quixadá / CE

## Apresentação

Formado em Técnico em Informática pelo Instituto Federal de Ciência e Tecnologia do Rio Grande do Norte (IFRN), Técnico em Informática para web pelo Instituto Metrópole Digital (IMD) e graduando em Ciência da Computação pela Universidade Federal do Ceará (UFC). Participou do desenvolvimento do projeto SISADEV, com o intuito de desenvolver um dispositivo que auxilia deficientes visuais a conseguir utilizar transporte público de forma independente. Já fui bolsista de iniciação científica em Inteligência Artificial com foco em Planejamento Automatizado e, atualmente, bolsista de Inovação Tecnológica com foco no processamento de impressões digitais e reconhecimento de padrões e mentor parceiro do projeto Cientista Beta.

## Outras Informações

Estou no penúltimo ano da graduação e realizando estágio, então por enquanto, só posso aceitar trabalhos remotos ou freenlancers. A partir de 2020, quando já estiver concluido, já terei disponibilidade para assumir em qualquer cidade (Brasil ou exterior).

## Especialidades

- Java
- Spring Boot e Security
- Python
- C / C++
- Haskell
- PostgreSQL
- MySQL
- Linux
- Git / Bitbucket / Gitlab
- Inteligência Artificial (Planejamento Automatizado)
- Aprendizado de máquina
- Apps cliente - servidor
- Inglês (Leio e escrevo muito bem, compreendo e falo bem)
- Espanhol (Leio e compreendo bem, escrevo e falo pouco)

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/rodmds/

## Site

https://github.com/RodMdS

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
