### ISSUE TITLE
[Quixadá/CE] Natanael da Silva Araujo

### ISSUE THREAD

**Issue by natanael-silvamt** [backend-br/me-contrata#17]
## Nome completo

Natanael da Silva Araujo

## Localidade

Quixadá / CE

## Apresentação

Atualmente sou aluno do curso de Ciência da Computação na Universidade Federal do Ceará - UFC, sou bolsista de Inovação Tecnológica pela Funcap. Possuo técnico em informatica, com enfase em desenvolvimento de sistemas, já trabalhei como estagiário em uma empresa de TI. Hoje meu foco é a carreira de desenvolvedor full stack.

## Outras Informações

Atualmente minha disponibilidade está comprometida devido aos horários da faculdade e também do projeto que sou bolsista. Ficando a disponibilidade para novas oportunidades apenas remotamente, más após a conclusão do meu curso terei total disponibilidade para atuar presencialmente em qualquer lugar(Nacional / Internacional).

## Especialidades

- Java
- Spring Boot e Security
- C++
- Python
- Django
- Bootstrap
- JavaScript
- React
- PostgreSQL
- MySQL
- Oracle
- Linux
- Git / GitLab
- Machine Learning

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/natanael-silva/

## Site

https://github.com/natanael-silvamt

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
