### ISSUE TITLE
[Guaratuba/PR] Douglas Louterio

### ISSUE THREAD

**Issue by Dougwan** [backend-br/me-contrata#19]
## Nome completo

Douglas M.M Louterio

## Localidade

Guaratuba / PR

## Apresentação

​Procuro oportunidades na área de tecnologia, principalmente envolvendo
programação, onde eu possa trabalhar com projetos desafiadores, e que me tragam novos
aprendizados. Meu último trabalho foi como suporte TI na empresa 2Rios Lingerie, atuei como estagiário durante 5 meses.

## Outras Informações

Atualmente moro no litoral do Paraná, mas posso me mudar caso precise, de preferência procuro oportunidades em regiões próximas, como Curitiba ou Joinville. Atualmente estudo e prático as tecnologias Javascript e NodeJS.

## Especialidades

- JavaScript - Básico/Intermediário
- NodeJS - Básico
- HTML - Básico
- CSS - Básico
- PHP - Básico

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/douglas-louterio/

## Site

https://twitter.com/_Dougwan

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
