### ISSUE TITLE
[ Rio de Janeiro/RJ ] Anderson Toledo Martins Moreira

### ISSUE THREAD

**Issue by atmmoreira** [backend-br/me-contrata#2]
## Nome completo

Anderson Toledo Martins Moreira

## Localidade

Rio de Janeiro.

## Apresentação

> Eu trabalho como UI Specialist Designer com tecnologias como photoshop, illustrator, figma, html5, css3, sass, javascript (jquery) e bootstrap. Hands-on desde 2013 construindo projetos com wordpress. Gerenciamento de código com bitbucket e github. Adepto ao uso de metodologias como scrum e kanban. 

>Frontend Software Developer, desde 2019 desenvolvendo soluções utilizando tecnologias como javascript, web components, react.js, styled-components e css-in-js. Meu objetivo é me tornar Fullstack Software Engineer na stack: javascript, typescript, react.js, node.js e php.

>Estou aprendendo outras tecnologias como typescript, laravel, redux, react testing library, next.js, nest.js, jest, unit tests, tdd, object-oriented programming, design patterns, micro frontends, graphql, gatsby, jamstack, clean code and clean architecture.

## Outras Informações

> Disponível para mudança de Cidade/País e trabalhos remotos.

## Especialidades

>Habilidades Técnicas\
15 anos: adobe illustrator e ui design experience.
10 anos: html5, css3, adobe photoshop, wordpress, bootstrap, zurb foundation e materialui.
4 anos: javascript, jquery, webpack, sass-scss, block-element-modifier (bem), figma, mysql, git, github, bitbucket e php.
1-2 anos: react.js, node.js, mongodb, axios, fetch, styled-components, css-in-js, web components, leaflet.js e tailwindcss.
Aprendendo: typescript, laravel, redux, react testing library, next.js, nest.js, jest, unit tests, tdd, object-oriented programming, design patterns, micro frontends, graphql, jamstack, clean code e clean architecture.

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

> Github: https://github.com/atmmoreira
> LinkedIn: https://linkedin.com/in/atmmoreira 

## Site

> Portfolio: https://atmm.dev

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
