### ISSUE TITLE
[Fortaleza/CE] Romulo Xavier

### ISSUE THREAD

**Issue by romulo-xavier25** [backend-br/me-contrata#20]
## Nome completo

Romulo Xavier de Sousa

## Localidade

Fortaleza / CE

## Apresentação

Sou formado em Análise e Desenvolvimento de Sistemas, gosto muito de atuar como Desenvolvedor Back-End PHP.
Hoje estou focando meus estudos em Testes no PHP, usando PHPUnit e um pouco em VUE.js.
Trabalhei por mais de quatro anos como Desenvolvedor Front-End WordPress na criação de themas do zero e responsivo com Bootstrap e trabalhei em outra empresa como desenvolvedor php por um ano e meio. Em ambas empresas tive oportunidade em trabalhar home office.
Em meio acadêmico foquei no desenvolvimento Back-End em PHP e Java, na maioria dos projetos realizados foram com essas tecnologias.
Gosto muito de participar de eventos de tecnologia das comunidades PHP com Rapadura e WordPress Fortaleza.

## Outras Informações

Atualmente moro Fortaleza. Tenho disponibilidade para trabalhar em horário comercial. Atualmente estudo e prático as tecnologias PHP(Laravel, WordPress e PHPUnit).
No inicio fiz bastante cursos profissionalizantes na área da TI.

## Especialidades

- HTML5 - Avançado
- CSS3 - Avançado
- Bootstrap - Intermediário/Avançado
- JavaScript - Básico/Intermediário
- JQuery - Básico/Intermediário
- AngularJS - Básico
- VUE - Básico
- PHP - Intermediário/Avançado
- Laravel - Intermediário
- Composer  - Básico/Intermediário
- POO - Intermediário
- MySQL - Básico/Intermediário
- WordPress - Intermediário

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/romulo-xavier/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
