### ISSUE TITLE
[Corrente/PI] Felipe Santos

### ISSUE THREAD

**Issue by fgsantosti** [backend-br/me-contrata#22]
## Nome completo

 Felipe Gonçalves dos Santos

## Localidade

 Corrente / Piauí 

## Apresentação

 Graduado em Sistemas de Informação pela Universidade Federal do Piauí, pós-graduado em Redes e Segurança de Sistemas pela INTA e mestrado em Sistemas de Comunicação e Automação pela Universidade Federal Rural do Semi-Árido, atuando principalmente com Programação para a Web, Desktop e Mobile.

## Outras Informações

 Tenho disponibilidade para:
- Trabalhar durante manhã e noite;
- Realizar viagens para possíveis reuniões presenciais;
- Fazer cursos e participações em eventos e palestras. 

## Especialidades

- JavaScript
- HTML
- CSS
- PHP
- JAVA 
- Python
- Ruby
- C
- SQL
- PostgreSQL
- MySQL
- Linux
- Git
- Inteligência Artificial (Planejamento Automatizado)
- Aprendizado de máquina
- Inglês (Leio e escrevo muito bem, compreendo e falo pouco)
- Espanhol (Leio e compreendo bem, escrevo e falo pouco)

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

 [www.linkedin.com/in/felipegsantosti ](url) 

## Site

https://github.com/fgsantosti

**Comment by CamillaMoriya** [comment]
Olá Felipe, como vai?
Meu nome é Camilla e trabalho no Alfacon. Gostaria de conversar contigo sobre novos desafios.
Se tiver interesse, entre em contato comigo no 45 99833 3112 ou camilla.moriya@alfaconcursos.com.br
Abs, Camilla

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
