### ISSUE TITLE
[Rio de Janeiro/RJ] Rodrigo Tenorio

### ISSUE THREAD

**Issue by rt3norio** [backend-br/me-contrata#23]
## Nome completo

Rodrigo Garutti Tenorio

## Localidade

Rio de Janeiro - Ramos

## Apresentação

Já trabalhei em diversos ramos da informática: Suporte, Virtualização, Cabeamento Estruturado. E agora desejo ingressar na análise e desenvolvimento de sistemas, voltado para backend.

## Outras Informações

Disponibilidade de horario: Total
Viagens: Total
Mudança: Total

## Especialidades

- Javascript
- Ruby on Rails
- Java
- Python
- Linux
- Virtualização

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior
## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/rt3norio

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
