### ISSUE TITLE
[São Paulo/SP] Henrique Silva

### ISSUE THREAD

**Issue by mundodehads** [backend-br/me-contrata#24]
## Nome completo

Henrique Alves da Silva

## Localidade

São Paulo - SP

## Apresentação

Me chamo Henrique, sou formado em Ciência da Computação e em 2018 vim para São Paulo atuar com arquiteturas modernas (microsserviços e serverless) e buscar novos desafios. Desde então trabalho com Node.JS e Cloud em metodologia agil, atualmente gostaria de trabalhar remoto pois faz parte do meu planejamento pessoal.

## Especialidades

- JavaScript
- Node js
- Desenvolvimento de APIS
- Cloud publica/privada
- Arquitetura Serverless / Microservices

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://linkedin.com/in/henriquedsilva

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
