### ISSUE TITLE
[Rio de Janeiro/RJ] Eduardo Santos

### ISSUE THREAD

**Issue by OpsRJ** [backend-br/me-contrata#25]
## Nome completo
Eduardo F. dos Santos

## Localidade

Rio de Janeiro/RJ

## Apresentação

Me chamo Eduardo, tenho 35 anos e sou formado em Engenharia da Computação pela Uniceub - Brasília. Atualmente estou fazendo Pós em Segurança da Informação pela Universidade Estácio de Sá - RJ. Atuao na área de desenvolvimento de sistemas há 15 anos sendo especializado na linguagem Java. Possuo também conhecimento em Python e Go. Durante este tempo, tive a oportunidade de trabalhar em todas as etapas de desenvolvimento de um sistema. Sou especialista em arquitetura de software trabalhando com arquitetura de aplicações de alta disponibilidade utilizando padrões REST com Microserviços e Cloud (Amazon).

## Especialidades

- Java

- Python

- Go

- PHP

- Javascript

## Nível

- [ ] Estágio
- [] Júnior
- [ ] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/eduardo-santos-649b59145/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
