### ISSUE TITLE
[Campinas/SP] Roberto Souza

### ISSUE THREAD

**Issue by souzajr** [backend-br/me-contrata#26]
## Nome completo

Roberto Souza

## Localidade

Campinas/SP

## Apresentação

Sou estudante de Sistemas da Informação na PUC Campinas e trabalho como freelancer há mais de dois anos. Em meus anos de experiência, atuei em diversas áreas e com tecnologias diferentes: configuração de servidores, desenvolvimento de aplicativos, diversos frameworks, ecommerce, gateways de pagamento, entre outros. Minha especialização é em aplicações voltadas para web.

## Outras Informações

Tenho disponibilidade durante o horário comercial e nos finais de semana. Posso ir para São Paulo ou para as cidades da RMC.

## Especialidades

- JavaScript
- HTML
- CSS
- AWS
- MongoDB
- NodeJS

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

Whatsapp: (19) 9 9587-7791

## Site

Portfólio: https://purpletech.com.br/#portfolio
Repositório: https://github.com/souzajr

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
