### ISSUE TITLE
[São Paulo/SP] Rogério Salvadeo

### ISSUE THREAD

**Issue by rogersalvadeo256** [backend-br/me-contrata#27]
## Nome completo

Rogério Salvadeo Vieira

## Localidade

São Paulo/SP

## Apresentação

Estudo programação desde os 15 anos, e iniciei estudos mais profundos quando entrei na ETEC Jaraguá no curso de Técnico em Informática com foco em programação, desde então iniciei estudos envolvendo várias áreas como hardware e software, com conhecimento avançado em Java, C# e PHP e conhecimento básico de Javascript.

## Outras Informações

Em constante evolução e estudos sobre novas técnologias e como aplica-las da melhor maneira, seja em quesitos de software, seja em hardware.

## Especialidades

- JavaScript
- HTML
- CSS
- PHP
- C#
- .Net
- Java
- MySQL
- NodeJS
- Arduino
- Manutenção de micros

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/roger-v-851199130/

## Site

https://github.com/RogerFerraro256

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
