### ISSUE TITLE
[Carapicuiba/SP] Wilton Alves

### ISSUE THREAD

**Issue by CodexZombie** [backend-br/me-contrata#28]
## Nome completo

Wilton da Silva Alves

## Localidade

Carapicuiba/SP (Região metropolitana da Zona Oeste).

## Apresentação

Técnico em Design Gráfico na ETE Carapicuíba (2009) e em Informática pela ETE Basilides de Godoy (2015), inglês intermediário, conhecimentos básicos em HTML, CSS, JavaScript, MySQL, UML e intermediário em C# e Python.

Busco minha primeira posição na área de programação como programador back end júnior (ou assistente). 

## Outras Informações

Tenho disponibilidade para inicio imediato, horários (tarde) a partir das 14:00 ou (manhã) até as 18:00 (porque pretendo retomar a graduação na FATEC em Análise e Desenvolvimento de Sistemas)

## Especialidades

- Python
- C#

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/wiltonalves/

## Site

https://github.com/CodexZombie

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
