### ISSUE TITLE
[Porto Velho/RO] Gabriel Flauzino

### ISSUE THREAD

**Issue by flaugabriel** [backend-br/me-contrata#31]
## Nome completo

 Gabriel Flauzino Mota. 

## Localidade

 Porto Velho / Rondônia. 

## Apresentação

 Atuo na área de desenvolvimento de softwares focando em serviços web há 2 anos, formado em sistemas de informação em 2018.

## Outras Informações

Disponibilidade durante a tarde e toda noite. 

## Especialidades

- JavaScript
- HTML
- CSS
- Ruby
- Ruby on Rails
- Mysql
- Postgres
- Git 
- Gitlab
- Docker
- Oracle
- Flutter 
- Dart
- JQuery

## Nível

- [ ] Estágio
- [] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total

## Contato
 https://www.linkedin.com/in/gabriel-flauzino-484927b8 
https://flaugabriel.github.io/gabrielflauzino/
https://stackshare.io/flaugabriel/my-stack

**Comment by palomagarcel** [comment]
Olá, o James está com vaga>>
https://james.gupy.io/jobs/1289910

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
