### ISSUE TITLE
[Novo Oriente/CE] Bruno Sousa

### ISSUE THREAD

**Issue by brunosousadev** [backend-br/me-contrata#38]
## Nome completo

Bruno Teixeira de Sousa

## Localidade

Novo Oriente / CE

## Apresentação

Técnico em Informática e Bacharelando em Ciência da Computação, um amante de programação. Podendo atuar como full stack dev, 3 anos de experiência trabalhando com desenvolvimento de software e aplicativos. Desenvolvendo pesquisa no campo da Pesquisa Operacional. 

## Outras Informações
Cursos 
- Java 8
- Spring Boot
- Javascript
- Javascript ES6+
- NodeJS
- ReactJS
- React Native
- Git

## Especialidades

- Java
- Spring Boot
- SQL
- MySQL
- Python
- C++
- JavaScript
- CSS
- Git
- SCRUM
- Android

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

 https://www.linkedin.com/in/brunosousa01/

## Site

https://brunosousadev.github.io/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
