### ISSUE TITLE
[Rio de Janeiro/RJ] Gabriel Mattos

### ISSUE THREAD

**Issue by gabrielsousadev** [backend-br/me-contrata#39]
## Nome completo

Gabriel Mattos da Silva Sousa

## Localidade

Rio de Janeiro / RJ

## Apresentação

Olá, sou Gabriel, sou formado em Técnico em Informática pela FAETEC, e estou cursando Ciências da Computação pela UNICARIOCA.

Atualmente atuo como Técnico I na CISCEA - Comissão de Implantação do Sistema do Controle do Espaço Aéreo, através da CTCEA - Organização Brasileira para o Desenvolvimento Científico e Tecnológico do Controle do Espaço Aéreo desde o ano de 2017 até então.

Também sou desenvolvedor de jogos utilizando a game engine Unity, desde 2016, e já publiquei alguns jogos na Google Play.

Criador do projeto Royals Studios, com o objetivo de produzir jogos mobile gratuitos para dispositivos móveis: https://www.facebook.com/RoyalsGamesStudios/

Atualmente também iniciei o estudo no desenvolvimento de aplicativos Android, utilizando Kotlin, Java e Material Design.

Possuo Github onde incluo projetos de estudo sobre diversos temas, principalmente Android, Unity e outros:
https://github.com/GabrielMattos 

## Outras Informações

Cursos Realizados:

- The Complete Android Material Design Course
- Kotlin Basics
- Curso Completo do Desenvolvedor Android (JAVA) - Faça 15 Apps
- C# Beginner / Intermediate
- Unity Certification
- Learn to Code by Making Games - The Complete Unity Developer
- Git e Github para iniciantes
- Jogos multiplayer online: Unity + Photon Pun (2019)

Idiomas:
- Inglês(Intermediário)
- Espanhol(Básico) 

## Especialidades

- Unity
- C#
- Blender
- Android Studio
- Kotlin
- Java
- Material Design
- Firebase

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Contato

https://www.linkedin.com/in/gabriel-mattos-9a849a9a/

## Site

https://www.facebook.com/RoyalsGamesStudios/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
