### ISSUE TITLE
[São Paulo/SP] Mateus Siqueira

### ISSUE THREAD

**Issue by themsiqueira** [backend-br/me-contrata#43]
## Nome completo

 Mateus Siqueira. 

## Localidade

 Jacareí/SP

## Apresentação

Já trabalhei um pouco com front-end, back-end e mobile, tenho mais ou menos 2,5 anos com experiência em desenvolvimento, gosto trabalhar em equipe, acredito muito em compartilhar conhecimento

## Outras Informações

Disponibilidade para mudança para São Paulo e para Viagens

## Especialidades

- JavaScript
- HTML
- REACTJs
- C#
- Docker
- .NET
- ES6

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [X] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [X] Remoto - Total
- [x] Alocado

## Contato

 https://linkedin.com/in/mateus-siqueira-439ab0bb

## Site

github.com/themsiqueira

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
