### ISSUE TITLE
[São Paulo/SP] Mateus Leal

### ISSUE THREAD

**Issue by mateus228leal** [backend-br/me-contrata#44]
## Nome completo

Mateus Abilio Gomes Leal

## Localidade
São Paulo/SP - Ipiranga

## Apresentação

Venho trabalhando como desenvolvedor desde junho deste ano. Iniciei como Freelancer desenvolvendo aplicativo Desktop em framework JavaScript. Atualmente trabalho formalmente como Full Stack junior usando Laravel com o blade engine do próprio framework como front-end. Também continuo trabalhando como freelancer, agora em equipe, onde usamos Laravel e Angular como stack de trabalho.

## Outras Informações

Como mencionado, atualmente trabalho formalmente, porém aberto a novas oportunidades que inclusive também como Full Stack ou Front-end.

## Especialidades

- JavaScript
- TypeScript
-Angular
- HTML
- CSS
- Sass
- PHP
- Laravel

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/mateus228leal

**Comment by lpliao** [comment]
https://jobs.kenoby.com/inatel

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
