### ISSUE TITLE
[Belo Horizonte/MG] Arthur Tavares

### ISSUE THREAD

**Issue by arthurtavaresdev** [backend-br/me-contrata#46]
## Nome completo

Arthur Flávio de Abreu Tavares

## Localidade

Belo Horizonte/MG

## Apresentação

Sou desenvolvedor PHP, atualmente trabalhando com Laravel, com notavel conhecimento em JavaScript (NodeJS).

## Outras Informações

- Atualmente estou cursando análise e desenvolvimento na Newton Paiva
- Técnico em informática (com foco em desenvolvimento) completo
- Horários Disponíveis: 7h as 19h.

## Especialidades

- JavaScript
- HTML
- CSS
- PHP
- Magento
- Laravel
- NodeJS

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

- Linkedin: https://www.linkedin.com/in/arthur-abreu-tavares/
- Email: hello@arthurtavares.dev
- Telefone : (31) 98277-3737

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
