### ISSUE TITLE
Procuro Emprego

### ISSUE THREAD

**Issue by dodo1210** [backend-br/me-contrata#48]
Nome completo

Douglas Siqueira Gonçalves

Localidade

[Picos/PI]

Apresentação

Sou Douglas, moro em Picos, PI. Atualmente tenho a formação bacharel em Sistemas de Informação pela Universidade Federal do Piauí na cidade de Picos. Meu último emprego foi como Analista e Desenvolvedor Jr. na linguagem Ruby, mas tenho uma maior afinidade com HTML, CSS, PYTHON e DJANGO

Outras Informações

Minha intenção é trabalhar de forma remota, mas estou disposto a realizar viagens de trabalho se a empresa necessitar

Especialidades

Front-End
- HTML, CSS, Bootstrap, JavaScript, React JS

Back-End
- C, Python, Django, Ruby , Ruby on Rails, Elixir, Java

Banco de Dados
- ElasticSearch, SQL (MySQL e PostgreSQL), MongoDB

Demais Áreas ou Ferramentas
- Brokers de Menssagem, Scraping, Git, I.A. com Python, Scrum, Microserviços

Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

Contato

https://www.linkedin.com/in/douglas-siqueira-48369b198/

**Comment by gustavofreze** [comment]
v
