### ISSUE TITLE
[Taubaté/SP] Fabiano Freitas

### ISSUE THREAD

**Issue by fabianosf** [backend-br/me-contrata#49]
## Nome completo

Fabiano Sousa de Freitas

## Localidade

Taubaté(SP)

## Apresentação

Eu tenho aproximadamente 10 anos de experiencia na area de TI, iniciei minha experiência professional um pouco antes de me formar em Rede de Computadores pela Estacio de Sa no Rio de Janeiro, foi em 2008 na Figwal que é uma empresa de médio porte especializada em transportes internacionais aonde permaneci 2 anos e buscando o meu desenvolvimento profissional eu trabalhei na Globo e Stefanini que são grandes empresas e referências no Mercado e apos isso resolvi abrir meu proprio negócio (Lan House) aonde permaneci por 5 anos e meio. Logo apos a minha mudanca para Taubaté realizei um projeto temporário na Volkswagen, mas infelizmente nao criaram uma posicão definitiva.Escolhi  a linguagem java pois  sempre tive interesse e aptidão para aprender. Tenho muitos amigos que ja trabalham na área e trocamos ideias e experiências.

## Outras Informações

Disponibilidade total. 
Jug 14 - Participação de Encontro de Usuários Java do Vale do Paraíba (São José dos Campos)
Jug 15 - Participação de Encontro de Usuários Java do Vale do Paraíba (Lorena)

## Especialidades

<!--
- JavaScript
- HTML
- CSS
- Java
- Vue
- Maven
- Spring Boot
- Spring Data
- Spring DevTools
- Jpa
- H2
- MySQL

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [] PJ
- [x ] CLT
- [ x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/fabianosfreitas/

## Site

https://fabianosf.github.io/fabianosf/

**Comment by lpliao** [comment]
https://jobs.kenoby.com/inatel/job/desenvolvedor-java-i-home-office/60117510c11b1128ce24304c?utm_source=website

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
