### ISSUE TITLE
[Guarulhos/SP] Lucas da Silva Lima

### ISSUE THREAD

**Issue by lucassilva996** [backend-br/me-contrata#50]
## Nome completo

Lucas da Silva Lima

## Localidade

Guarulhos/SP

## Apresentação

Atuo a 5 anos na área de Suporte e Infraestrutura com maior atuação em ambientes Windows, onde presto suporte aos notebooks, desktops e servidores, desde configurações de estações de trabalho até implantação de servidores na rede, virtualização e criação de ambientes utilizando containers. Abaixo algumas habilidades e competências que possuo. Linux - Windows – Mac Os Linguagens de Programação: Php, JavaScript, Html5 e CSS3, C#, Asp.Net Core MVC, Python

Busco oportunidade para poder migrar da área de Infraestrutura para a área de Desenvolvimento de Sistemas, estou me aperfeiçoando em .NET Core na linguagem C# utilizando a plataforma web Asp.Net Core MVC e também PHP utilizando o banco de dados MYSQL. Estou sempre disposto a aprender afim de me aperfeiçoar profissionalmente e agregar valor a empresa.

## Outras Informações
Cursos:
DESENVOLVIMENTO WEB COM PHP E MYSQL – UDEMY – 02/2020

ARQUITETURA DE SISTEMAS AVANÇADO – DIGITAL INNOVATION ONE – 01/2020

BOOTCAMP DE FÉRIAS COM .NET 2020 – DIGITAL INNOVATION ONE – 01/2020 

DESENVOLVIMENTO DE APLICAÇÕES COM .NET– DIGITAL INNOVATION ONE – 01/2020 

FUNDAMENTOS DE ARQUITETURA DE SISTEMAS – DIGITAL INNOVATION ONE – 01/2020

INTRODUÇÃO AO GIT E CONTROLE DE VERSÕES– DIGITAL INNOVATION ONE – 01/2020

INTRODUÇÃO AO GITHUB – DIGITAL INNOVATION ONE – 01/2020

PROJETOS ÁGEIS COM SCRUM – DIGITAL INNOVATION ONE – 01/2020

1939 – UMA VISÃO COMPLETA DO ASP.NET MVC – BALTA.IO – 11/2019

ASP NET MVC COM SQL – UDEMY – 11/2019 

1962 – INTRODUÇÃO AO C# E IMERSÃO AO .NET FRAMEWORK– BALTA.IO – 10/2019

7181 – COMEÇANDO COM ANGULAR– BALTA.IO – 10/2019

## Especialidades

- .Net Core
- C#
- PHP
- Python
- HTML, CSS, JavaScript

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

Linkedin - https://www.linkedin.com/in/lucas-da-silva-lima-38a81011b/ 

## Site

GitHub - https://lucassilva996.github.io/portfolio/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
