### ISSUE TITLE
[Cubatão/São Paulo] Vitor Hugo Xavier dos Santos Arruda

### ISSUE THREAD

**Issue by hugovitox** [backend-br/me-contrata#52]
## Nome Completo

Vitor Hugo Xavier dos Santos Arruda

## Localidade

Cubatão/São Paulo

## Apresentação

Formei à nível técnico no Instituto Federal de São Paulo, além de cursos extras em grandes universidades no exterior, tais como: Harvard Business School e New York University. Após a formação de nível técnico integrado ao ensino médio, ingressei no Instituto Tecnológico da Aeronáutica (ITA), entretanto durante esse ano precisei sair por questões de saúde. Atualmente estudo estatística na Universidade Federal de São Paulo (USP) e matemática na Universidade Metropolitana de Santos (UNIMES Virtual) e sou CEO de uma startup chamada Hain Corporation, a qual produz e distribui dispositivos capazes de detectar câncer cerebral.

## Outras Informações

Estou disponível no período da noite (em caso de Home Office). Disponível também para viagens com dias à combinar, entretanto não estou para mudanças, pois preciso continuar minhas atividades em São Paulo.

## Especialidades

- JavaScript
- HTML
- CSS
- PHP
- C#
- C
- Java
- node 
- Phyton
- VB.Net
- Kotlin

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

http://linkedin.com/in/vitor-hugo-17a029178

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
