### ISSUE TITLE
[SÃO MATEUS/ES] Rafael Emery

### ISSUE THREAD

**Issue by RafaelEmery** [backend-br/me-contrata#53]
## Nome completo

Rafael Emery Cade Poloni

## Localidade

São Mateus, ES

## Apresentação

Atualmente, entusiasta de Desenvolvimento Web com muita proatividade, ou seja, sempre buscando aperfeiçoar os conhecimentos tanto em hard skills, com constantes estudos como Frameworks e APIs Rest, quanto em soft skills, como comunicação.

Trabalhei dois anos na Adapti Soluções Web e sou graduando em Ciência da Computação. Tive diversas experiências com clientes: vendas e relacionamentos com stakeholders. Hoje me dedico a programação Web integralmente e gostaria de uma oportunidade aprender e aplicar tudo que aprendo, além de me desenvolver, participar e contribuir para uma organização e sua cultura.

## Outras Informações

Tenho disponibilidade total atualmente (período de isolamento social). Minha única obrigação é a universidade, e preciso de um horário flexível porém é fácil inserir outros compromissos em meu cotidiano.

Moro em São Mateus porém nasci, cresci em Vitória (ES), logo tenho possibilidade de me mudar.

## Especialidades

- HTML
- CSS
- JavaScript
- Bootstrap 4
- PHP
- Laravel 7
- Básico em NodeJS, ReactJS e React Native
- Conhecimento em APIs Rest
- Git e GitHub
- Ambiente Linux
- Metodologias Ágeis
- Inglês avançado

## Nível

- [X] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://rafaelemery.github.io 
https://www.linkedin.com/in/rafael-emery-c-poloni-310a35165/ 

## Site

https://github.com/RafaelEmery

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
