### ISSUE TITLE
[São Paulo/SP] Patrick Aguiar

### ISSUE THREAD

**Issue by letsaguiar** [backend-br/me-contrata#55]
## Nome completo

Patrick de Aguiar Silva

## Localidade

São Paulo, SP

## Apresentação

Estudante da Universidade de São Paulo, graduando em Gestão Pública e apaixonado por programação. Desde os 14 anos estudo programação e cheguei a participar de olimpíadas como a OBI. Na vida acadêmica, acabei por seguir por outro caminho e me afastei da área, mas durante a quarentena retomei meus estudos e me vi novamente passando longas e longas horas na frente do computador.

Dessa vez, segui para a programação web. O inglês amadurecido me deu a oportunidade de estudar desenvolvimento web com o CS50 - famoso curso de Harvard - e até o momento completei 4, todos disponíveis no meu perfil do GitHub. O interesse pela computação cresceu tanto nos últimos meses que hoje tento me recolocar no mercado, com uma possível transferência de curso ao final do ano. Além das habilidades com programação, sou extremamente pragmático e organizado, o que me ajuda imensamente na divisão entre estudo e prática e acredito que possa ser de grande valor nas atividades reais de trabalho.

## Outras Informações

Atualmente, tenho disponibilidade absoluta. As aulas EaD me dão uma grande disponibilidade de horário. Quanto à formação e habilidades, acho que vale a pena destacar três ferramentas: Learning Python the Hard Way ( o livro com o qual eu retomei meus estudos em programação),  CS50 Web ( o curso com o qual tenho aprendido sobre desenvolvimento web e feito meus primeiros projetos) e Web Development Roadmap (o repositório no GitHub que tem me ajudado a acumular mais skills além das oferecidas pelo curso).

## Especialidades

HTML, CSS, JavaScript e Python-Django

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/patrick-aguiar-85b86516b/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
