### ISSUE TITLE
 [Belo Horizonte/MG] Breno Cota

### ISSUE THREAD

**Issue by brenogcota** [backend-br/me-contrata#56]
## Nome completo

Breno Gonçalves Cota

## Localidade

Belo Horizonte / MG

## Apresentação

Entusiasta Javascript, procuro novos desafios e a oportunidade de estar sempre aprendendo. Focado no desenvolvimento da Web com o NodeJS e o ecossistema Javascript.

## Outras Informações

Atualmente resido na cidade de Berilo / MG, busco por vagas remotas ou na Região de Belo Horizonte

## Especialidades

- Node JS - Express 
- PHP - Laravel
- C#
- MySQL - PostgreSQL - MongoDB
- HTML
- CSS - Sass
- AWS

## Nível

- [x ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [x ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x ] Remoto - Total
- [] Alocado

## Contato

https://linkedin.com/in/breno-cota-a51711177/

## Site

https://github.com/brenogcota
[Currículo.pdf](https://github.com/backend-br/me-contrata/files/4960775/Curriculo.pdf)

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
