### ISSUE TITLE
[Rio de Janeiro/RJ] Allan Vigiani

### ISSUE THREAD

**Issue by allanvigiani** [backend-br/me-contrata#61]
## Nome completo

Allan Vigiani Ferreira Costa

## Localidade

Rio de Janeiro - Rio de Janeiro

## Apresentação

Me chamo Allan, tenho 20 anos e atualmente curso o 2° período de Engenharia de Software. Busco a primeira experiência no mercado de trabalho para por em prática tudo o que tenho estudo nos últimos meses e principalmente aprender com pessoas que estejam dispostas a me ensinar e me moldar da melhor forma possível. Já possuo alguns projetos com HTML, CSS e Java Script voltado para o Front-End. Atualmente estudo Python voltado para a área de Data Science.

## Outras Informações

Atualmente estou disponível na parte da manhã e da tarde pois estudo durante o período da noite. Estou disposto a me descolar para cidades vizinhas caso seja necessário.

## Especialidades

- Java Script
- Python
- HTML
- CSS
- PHP

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Presencial
- [x] Remoto - Parcial
- [x] Remoto - Total

## Contato

https://www.linkedin.com/in/allan-vigiani/

## Site

https://github.com/allanvigiani

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
