### ISSUE TITLE
[Santa Barbara d' Oeste/SP]

### ISSUE THREAD

**Issue by danitw** [backend-br/me-contrata#62]
## Localidade

Santa Barbara d' Oeste - São Paulo

## Apresentação

Meu nome é Daniel, tenho 16 anos e atualmente to indo atras do meu primeiro emprego, estudo principalmente PHP, JS, CSS Laravel, nodejs e vuejs

## Outras Informações

Estou disponivel pra trabalhar remoto, trabalha em outra cidade e ate me mudar, e se for necessario aprender novas tecnologias para o trabalho e também to disponivel o dia inteiro

Aceito freelas também

## Especialidades

- PHP
- HTML
- CSS
- Javascript
- Node.js
- Laravel
- Vue.js

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Presencial
- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/danitw

## Site

https://github.com/danitw

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
