### ISSUE TITLE
[São Gabriel da Palha/ES] Douglas dos Reis Couto

### ISSUE THREAD

**Issue by douglasreiscouto** [backend-br/me-contrata#64]
## Nome completo

Douglas dos Reis Couto

## Localidade

São Gabriel da Palha / Espírito Santo

## Apresentação

Sou apaixonado por Tecnologia, desenvolvimento e marcas que trabalhem para contribuir com uma melhor interação digital.

Estudo desenvolvimento de software e curso Análise e Desenvolvimento de Sistemas. Atuo na área de Tecnologia da Informação desde 2015, onde vivi experiências reais do dia a dia de um profissional de TI, com muito trabalho em equipe e mão na massa.

Tenho foco e acredito em ações que possam gerar um impacto positivo na vida das pessoas.

## Outras Informações

Em busca de trabalho remoto, no momento não tenho disponibilidade para me mundar, estou disponível de 08:00h as 18:00h, de Segunda a Sexta.

Cursos:
- Auditoria, qualidade e teste de software
- Banco de dados relacionais
- Cabeamento estruturado de redes
- Desenvolvimento back-end em PHP/Laravel
- Designer gráfico
- Informática Rápida
- Montagem e manutenção de computadores
- Programação funcional em C
- Programação orientado a objeto em C++
- Programação orientado a objeto em Java

## Especialidades

- PHP/Laravel
- Git 
- GitHub
- Java 
- C++ 
- HTML5
- CSS3 

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://linkedin.com/in/douglasreiscouto

## Site

https://douglas-reis.github.io/portfolio/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
