### ISSUE TITLE
[Goiânia/GO] Roberto Frederico

### ISSUE THREAD

**Issue by rsinet** [backend-br/me-contrata#68]
## Nome completo

Roberto Frederico Tôgo Santos

## Localidade

Goiânia/GO

## Apresentação

Experiência em análise, projeto e implementação, em linguagem de programação de
alto nível; gerência de configuração em infra­estrutura de desenvolvimento; 11 de experiência no desenvolvimento de infra­estrutura de transmissão e recebimento dos arquivos de urna dos Sistemas Eleitorais; desenvolvimento de infra­estrutura dos Sistemas de Divulgação de Eleições; 5 anos como arquiteto de software no TSE.

## Outras Informações

De 4 a 6hs diárias. Remoto.

## Especialidades

- Backend em Java;
- Mensageira;

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/mwlite/in/roberto-frederico-togo-santos-562a5630

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
