### ISSUE TITLE
[Remoto][Rio Claro - SP] Tarsis d Lima

### ISSUE THREAD

**Issue by brtmvdl** [backend-br/me-contrata#69]
## Nome completo
Tarsis Mikael Ventura Dumas de Lima

## Localidade
Rio Claro - SP

## Apresentação
Amo o que faço, gosto de novos desafios e sempre busco me atualizar. Gosto de aprender e ensinar o que aprendo para meus colegas de trabalho para que possamos evoluir juntos. Acredito que a boa comunicação e o trabalho em equipe são as chaves para a produtividade e crescimento profissional. Como desenvolvedor full-stack trabalho com a principais tecnologias do mercado React, Angular, Node.js, MongoDB, Docker, Linux e Git.

## Especialidades
* Node.js
* PHP
* Python
* MySQL
* PostgreSQL
* MongoDB
* GraphQL
* RESTful API
* Docker
* Git
* SVN
* HTML
* CSS
* JavaScript
* Typescript
* React
* Angular 2+

## Tempo de experiência
* [ ]  < 1 ano
* [ ]  > 1 ano
* [ ]  > 2 anos
* [x]  > 5 anos

## Nível
* [ ]  Estágio
* [ ]  Júnior
* [x]  Pleno
* [x]  Sênior

## Tipo de contratação
* [x]  CLT
* [x]  PJ
* [x]  Freela

## Tipo de trabalho
* [x]  Remoto - Total
* [x]  Remoto - Parcial
* [x]  Alocado

## Contato
Linkedin - https://www.linkedin.com/in/tmvdl/
Telegram - https://t.me/tmvdl

## Site
Em desenvolvimento

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
