### ISSUE TITLE
[Santo André/SP] Kaique Xavier Atalla

### ISSUE THREAD

**Issue by X-X-Xavito** [backend-br/me-contrata#7]
## Nome completo

Kaique Xavier Atalla

## Localidade

Santo André/SP

## Apresentação

Depois de atuar no mercado administrativo por quatro anos, me identifiquei com a área de 	tecnologia, em especial com a área de programação. Venho completando diversos cursos na plataforma Alura e busco por uma oportunidade para aprimorar minhas habilidades em desenvolvimento. 

## Outras Informações

Tenho disponibilidade de horário e viagens. Também tenho interesse em ensinar e ministrar cursos e palestras depois que pegar experiência e confiança.

## Especialidades

Conhecimentos básicos em:
- JavaScript
- HTML
- CSS
- PHP

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/kaique-atalla-3a1562125/

## Site

https://github.com/X-X-Xavito

**Comment by engaugusto** [comment]
Cara, vou dar 1 dica que talvez te ajude.
Estude Java,python,nodejs ou C#. Qualquer coisa mais para o lado do backend. 
Seu perfil parece bastante front.

Abraços !
