### ISSUE TITLE
[Remoto][Brasília/DF] Vinícius Jadiscke

### ISSUE THREAD

**Issue by Jadiscke** [backend-br/me-contrata#70]
## Nome completo

Vinícius Jadiscke de Souza Tasso

## Localidade

Brasília - Distrito Federal

## Apresentação

Desenvolvedor Node.js com conhecimentos de FrontEnd. Participei de um fomento de formação de profissionais aonde atuei como desenvolvedor node.js meio-período, o nome do projeto é [Lift Learning](https://liftlearning.com.br/) e é uma iniciativa da FENASBAC com o banco central. Trabalhei em um projeto para criação de um aplicativo para pessoas jurídicas para o Banco de Brasília.

## Outras Informações

Disponível: Manhã e Tarde.
Não possuo disponibilidade para me mudar.
Aceito Trabalhar remoto.
Atualmente estou procurando evoluir ao fazer o curso do @ErickWendel [Imersão em desenvolvimento de APIs com Node.js By #NodeBR!](https://cursos.erickwendel.com.br/)

## Especialidades

- JavaScript
- Node.js
- Express.js
- MongoDB
- PostgreSQL
- HTML
- CSS

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ (Ainda não possuo MEI)
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/viniciusjstasso/

## Site

https://www.github.com/Jadiscke

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
