### ISSUE TITLE
[Rio de Janeiro/RJ] Jonathan Mothé

### ISSUE THREAD

**Issue by jonathan-mothe** [backend-br/me-contrata#72]
## Nome completo

Jonathan Mothé

## Localidade

Rio de Janeiro / RJ

## Apresentação

Sou desenvolvedor Python e estou em busca de oportunidade em que possa dar continuidade a minha carreira. Atualmente moro na cidade do Rio de Janeiro. Tive uma breve experiência formal, desenvolvendo API REST com Django REST Framework e testes automatizados com Unit. Desde então venho buscando conhecimento para me recolocar profissionalmente.

## Outras Informações

Tenho disponibilidade para viagens e para mudanças.

## Especialidades

- Python
- Django
- Django REST Framework
- Fastapi
- Docker
- Postgres
- HTML
- CSS
- Javascript

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/jonathan-mothe

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
