### ISSUE TITLE
[Remoto][Fortaleza/CE] Jeferson Oliveira

### ISSUE THREAD

**Issue by Zuruckt** [backend-br/me-contrata#73]
## Nome completo

Francisco Jeferson da Silva de Oliveira

## Localidade

Pacajus, CE

## Apresentação

Sou um desenvolvedor backend com foco em PHP, mais especificamente usando o framework Laravel. Tenho experiência como estagiário Fullstack usando o PHP  para um sistema de gerenciamento escolar, que faz parte da grade curricular do meu curso Devido a pandemia, este está em pausa e não há previsão de volta tão cedo, então decidi vir atrás da minha primeira oportunidade como desenvolvedor júnior.

## Outras Informações

- 40h semanais
- Não tenho disponibilidade para mudança
- Curso Técnico em Informática
- Membro da He4rt Developers

## Especialidades

- PHP
- Laravel
 -Lumen
- POO
- MVC
- MySQL
- Git
- HTML
- CSS
- JavaScript
- Inglês Básico - Intermediário

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/jefersonoliveira4

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
