### ISSUE TITLE
[Santa Maria/RS] Bruno Fialho

### ISSUE THREAD

**Issue by bruno-fialho** [backend-br/me-contrata#74]
## Nome completo

Bruno Germani Fialho

## Localidade

Santa Maria / RS

## Apresentação

Engenheiro Mecânico, entrei no mundo da programação através de cursos onlines, com destaque para CS50 - Harvard, Bootcamps Gostack (Fullstack) e Ignite (Node.js) - Rocketseat. Nesse ano de 2021 decidi focar 100% em Backend, pois é a área que mais me identifico.

## Outras Informações

Disponibilidade imediata, posso trabalhar remoto, e tenho disponibilidade para mudança.

## Especialidades

- Node.js
- Typescript
- OOP
- AWS
- Docker
- Postgres
- Typeorm
- Swagger
- Eslint
- Python
- C
- Java
- HTML

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/bruno-fialho/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
