### ISSUE TITLE
[REMOTO][Natal/RN] Cácio Lucas

### ISSUE THREAD

**Issue by caciolucas** [backend-br/me-contrata#76]
## Nome completo

Cácio Lucas Nobre de Almeida Bezerra

## Localidade

Natal, RN

## Apresentação

Eu sou Cácio Lucas, sou Técnico em Informática pelo IFRN e estudante do curso de Bacharelado de Tecnologia da Informação na UFRN. Atuo como desenvolvedor backend em um projeto de pesquisa, inovação e desenvolvimento. Tenho contato diário com seguintes tecnologias: Python, Django Rest Framework, PostgreSQL e Git. Bem como as metodologias SCRUM e Gitflow. Tive experiência com diversos frameworks web do Python, como Flask, Pyramid e Django. Tenho iniciado também estudos em outros frameworks back-end como Spring e .NET. 

## Especialidades

- Django
- Django Rest Framework
- Vue,js

#### Estudando

- Spring
- .NET
- Flutter

## Nível

- [x] Estágio 
  - Spring
  - .NET
  - Flutter
- [x] Júnior
  - Django
  - Django Rest Framework
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [X] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [X] Remoto - Total
- [ ] Alocado (Somente após fim da faculdade)

## Contato

https://linkedin.com/in/cacio-lucas

## Site

https://caciolucas.github.io/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
