### ISSUE TITLE
[Santo André - SP] Renan Rosa Deposito

### ISSUE THREAD

**Issue by RenanRosaDep** [backend-br/me-contrata#77]
## Nome completo

Renan Rosa Deposito

## Localidade

Santo André - SP

## Apresentação

Estou cursando o primeiro semestre de Análise e Desenvolvimento de Sistemas pelo SENAC. Atualmente realizo projetos pessoais utilizando a stack Node(Express) ou Java para o back-end. MySql, Postrgressql e MongoDB para o banco de dados. React ou Html e Css básico para o front-end.

## Outras Informações

Possuo disponibilidade total de horário.

## Especialidades

- JavaScript
- HTML
- CSS
- Java
- GIT

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/renanrosadeposito/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
