### ISSUE TITLE
[Amparo/SP] Giovanni de Godoy Moreira

### ISSUE THREAD

**Issue by Gvnn01** [backend-br/me-contrata#78]
## Nome completo

Giovanni de Godoy Moreira

## Localidade

 Amparo / São Paulo. 

## Apresentação

Desenvolvedor backend iniciante. Conhecimento em Python (Anaconda), Javascript (Node) e PHP.

## Outras Informações

 100% disponível. 

## Especialidades

- JavaScript
- HTML
- CSS
- PHP
- Python

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Contato

 https://linkedin.com/in/giovanni-moreira-70a765209 

## Site

https://github.com/Gvnn01

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
