### ISSUE TITLE
[Campinas/SP] Jackson Tenorio da Silva

### ISSUE THREAD

**Issue by jacksontenorio8** [backend-br/me-contrata#79]
## Nome completo

Jackson Tenorio da Silva

## Localidade
Campinas / SP 

## Apresentação

Olá eu me chamo Jackson, tenho 33 anos e moro atualmente em Campinas. Estou estudando tecnologia a um tempo no intuito de fazer uma transição de carreira

## Outras Informações

Tenho disponibilidade de horário, cursos e palestras

## Especialidades

- Programação Java: microserviços, spring boot, spring cloud, IntelliJ, SQL Sever e Docker.
- Programação Python (acadêmico): PostgreSQL, MongoDB, Bancos de Dados NoSQL, ETL, Hadoop, Spark,
Pandas, Pycharm, Jupyter Notebook e Visual Studio Code.
- Ambiente Linux : Ubuntu e Fedora.
- Git / Github
- Design UI / UX: conhecimentos básicos em front-end (HTML, CSS e Javascript).
- Google Cloud Platform
- AWS
- Azure

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/jacksontenorio8 

## Site

https://github.com/jacksontenorio8

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
