### ISSUE TITLE
[Sobral / CE] Matheus Araújo da Cunha

### ISSUE THREAD

**Issue by matheus-araujo-cunha** [backend-br/me-contrata#85]
## Nome completo

Matheus Araújo da Cunha

## Localidade

Sobral/CE

## Apresentação

Estudo desenvolvimento web há mais de 1 ano, sempre aprendendo novas ferramentas/tecnologias e colocando em prática com pequenos projetos!
Tenho o objetivo de ser um grande desenvolvedor, criando aplicações que possam ser utilizadas por várias pessoas ao dia a dia, de forma acessível e intuitiva.

## Outras Informações

Possuo disponibilidade entre 11h/15h e também 17h/19h.

## Especialidades

- JavaScript
- HTML
- CSS
- React
- Python
- Flask
- PostgreSQL
- MongoDB
- SQLalchemy
- NodeJS
- Express
- TypeScript
- GIT

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/matheusaraujocunha/

## Site

https://github.com/matheus-araujo-cunha

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
