### ISSUE TITLE
[Bragança Paulista/SP] Bruno Borelli

### ISSUE THREAD

**Issue by BrunoBorelliPro** [backend-br/me-contrata#86]
## Nome completo

Bruno Borelli

## Localidade

Bragança Paulista/SP

## Apresentação
Olá, meu nome é Bruno, tenho 20 anos, e quero me tornar um bom desenvolvedor. 🚀
Atualmente sou estudante do curso de Análise e Desenvolvimento de Sistemas do IFSP de Bragança Paulista e estou buscando uma oportunidade como dev jr. 📚
Sei um pouco de várias tecnologias, porém tenho confiança em Python e Django, mas claro que estou sempre disposto a aprender coisas novas. 👨‍💻

## Outras Informações

Estou disponível para contato das 8:00 até as 18:30.

## Especialidades

- JavaScript
- HTML
- CSS
- Python
- Django
- Java
- Spring
- Rest API
- Node JS
- Express
- MySQL

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

[https://linkedin.com/in/bruno-borelli](https://www.linkedin.com/in/bruno-borelli/)

## Site

[https://github.com/BrunoBorelliPro](https://github.com/BrunoBorelliPro)

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
