### ISSUE TITLE
[São Paulo/SP] Rafael Melo

### ISSUE THREAD

**Issue by RafaMeloP** [backend-br/me-contrata#87]
## Nome completo

Rafael Rodrigues de Melo Pereira

## Localidade

São Paulo/SP

## Apresentação

Sou formado em análise e desenvolvimento de sistemas, sou desenvolvedor Full Stack Junior, possuo 3 anos de experiência em desenvolvimento de software, 3 anos de HTML/CSS e Javascript, 2 anos de React js, 2 anos de linguagens SQL e 1 ano de Java e Spring Boot. Em busca de vagas utilizando React js ou Java.

## Outras Informações

Disponível das 08:00 as 18:00.

## Especialidades

- JavaScript
- HTML
- CSS
- React js
- Java
- Spring boot
- MySql

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

[https://linkedin.com/in/rafamelop](https://www.linkedin.com/in/rafamelop/)

## Site

[Github](https://github.com/RafaMeloP/)

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
