### ISSUE TITLE
[Itajaí/SC] Wyulle Santos

### ISSUE THREAD

**Issue by s4nts** [backend-br/me-contrata#88]
## Nome completo

Wyulle Sousa Santos

## Localidade

Itajaí / Santa Catarina.

## Apresentação

Olá!
Me chamo Wyulle Santos, sou estudante de Analise e Desenvolvimento de Sistemas, Estagiário na Employer Rh - BNE como DevOps e Desenvolvedor Back-End Jr com experiência em C# e Asp .NET. Busco sempre me inovar, cito como um de meus pontos mais fortes a curiosidade e inovação constante. Tenho contato diário com as seguintes tecnologias: C#, Asp .NET Framework, SQL Server Azure Pipelines, Azure DevOps e Git. Bem como SCRUM e Metodologia ágil. Tenho iniciado também estudos em outras tecnologias como Python, Docker e Kubernetes.

## Outras Informações

Estou disponível das 14h até as 00h. Esse horário pode ser alterado mediante análise da vaga.

## Tecnologias 

**Especialidades**
- C#
- .Asp .NET Core Framework
- SQL Server
- HTML
- CSS

**Estudando**
- Cultura DevOps
- Docker
- CI/CD
- Kubernetes
- Rabbit.mq
- WebApi
- Python
- Linux

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/wyullesantos/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
