### ISSUE TITLE
[São Luís/MA] Carlos Eduardo

### ISSUE THREAD

**Issue by cegalvao92** [backend-br/me-contrata#89]
## Nome completo

Carlos Eduardo Lima Galvão 

## Localidade

São Luís /MA

## Apresentação

Sou bacharel em ciência da computação, sempre gostei muito de tecnologia e os benefícios que ela proporciona tanto na vida social e profissional das pessoas. Estou sempre buscando atualizar e enriquecer meus conhecimentos na área, já realizei alguns cursos de Python, Java Script, Programação Orientada a Objetos, Node JS, entre outros. Sou apaixonado pela língua inglesa e sempre tento arrumar um tempo para aprimorar meu inglês, através de cursos, vídeos, textos e podcasts com esse objetivo. Atualmente busco uma oportunidade no mercado de trabalho na área de TI, como desenvolvedor Backend ou áreas correlatas com minha formação e experiências. 

## Outras Informações

Tenho disponibilidade pra trabalho remoto nas cidades fora da minha localidade e presencial ou remoto na minha cidade.
Sem disponibilidade pra mudanças no momento.
Sou formado em Ciência da Computação, com Pós-graduação em Gestão de Projetos, atualmente estou finalizando um curso de Desenvolvedor Backend.
[Carlos Eduardo Lima Galvão - Currículo-.pdf](https://github.com/backend-br/me-contrata/files/8791794/Carlos.Eduardo.Lima.Galvao.-.Curriculo-.pdf)

## Especialidades

- JavaScript
- HTML
- CSS
- PHP
- NodeJS
- TypeScript
- NestJS
- API RestFul
- MongoDB
- PostgreSQL

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/carlos-eduardo-lima-galvão-a92707174/

## Site

https://github.com/cegalvao92

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
