### ISSUE TITLE
[São Paulo/SP] Lucas Ferreira

### ISSUE THREAD

**Issue by lucassantos61** [backend-br/me-contrata#9]
## Nome completo

Lucas Ferreira dos Santos

## Localidade

São Paulo / SP

## Apresentação

Sou desenvolvedor desde 2016 formado pela FATEC em Análise e Desenvolvimento de Sistemas e venho procurando o aperfeiçoamento de minhas habilidades técnicas e interpessoais para sempre levando o meu melhor  para a equipe e aplicando boas praticas sempre que possível visando a qualidade e agilidade na entrega dos produtos. 

## Outras Informações

Tenho disponibilidade de horário e viagens. Também tenho interesse em ensinar e ministrar cursos e palestras pois acredito que a melhor maneira de evoluir e compartilhar conhecimento.

## Especialidades

- PHP
- Magento
- Laravel
- JavaScript
- Docker
- MySql
- HTML
- TDD
- SQL
- LINUX
- GIT
- OBJECT CALISTHENICS
- PSR-1, PSR-2 , PSR-3 e PSR-4
- MVC
## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/lucas-f-dos-santos

https://github.com/lucassantos61

**Comment by reginaldojunior** [comment]
@lucassantos61 pode me mandar seu e-mail?

**Comment by lucassantos61** [comment]
Claro que posso @reginaldojunior  lucasferreira241@gmail.com

**Comment by vinyvicente** [comment]
@lucassantos61 , ainda buscando?

**Comment by lucassantos61** [comment]
@vinyvicente  no momento não, muito obrigado.
