### ISSUE TITLE
[Macapá/AP] Yrllan Brandão

### ISSUE THREAD

**Issue by YrllanBrandao** [backend-br/me-contrata#90]
## Nome completo

Yrllan Brandão Braga

## Apresentação

Olá, me chamo Yrllan, atualmente estou cursando o último semestre do curso superior de tecnologia em redes de computadores, gosto bastante de estudar informática, especialmente programação e segurança da informação, ultimamente estou me dedicando para aperfeiçoar meus conhecimentos em Node.js, criando inúmeras aplicaçõese projetos, já fiz freelas e estou esperando um oportunidade para entregar valor e evoluir.

## Outras Informações

Estou disponível para freela e estágio

## Especialidades

- JavaScript
- Node.js
- HTML
- CSS
- EJS

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Contato

https://linkedin.com/in/yrllanbrandao

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
