### ISSUE TITLE
[Serra Azul/SP] Wílian Ansanello

### ISSUE THREAD

**Issue by wiliansanello** [backend-br/me-contrata#92]
## Nome completo

Wílian Tenan Ansanello

## Localidade

Serra Azul/SP

## Apresentação

Sou bacharel em Sistemas de Informação, e tenho experiência de mais de 10 anos com T.I. A maior parte da minha carreira trabalhei como Analista de Suporte, mas já trabalhei como desenvolvedor também, usando as linguagens Java e ADVPL, que é uma linguagem proprietária do sistema ERP Protheus, do grupo TOTVS .
Tenho ampla experiência com atendimento ao cliente, analisando e solucionando problemas técnicos, ou respondendo a dúvidas de utilização dos sistemas para os quais dei suporte. Como desenvolvedor, já trabalhei em um projeto com a metodologia Scrum, fiz customizações para o ERP Protheus , e desenvolvi um sistema sob demanda usando Java. 

## Outras Informações

Caso opte por me contratar, gostaria de cumprir aviso prévio no meu atual emprego. Tenho preferência em trabalhar no período diurno, estou em busca de um emprego home office ou híbrido.

## Especialidades

- Javascript
- Node
- React
- Java
- HTML 
- CSS
- Bootstrap
- MongoDB
- SQL Server
- PostgreSQL

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://linkedin.com/in/wiliansanello

## Site

https://github.com/wiliansanello

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
