### ISSUE TITLE
[São Paulo/SP] Rodolfo Araujo

### ISSUE THREAD

**Issue by RodolfoArauj0** [backend-br/me-contrata#94]
Procurando oportunidades como Fullstack Jr, Front-End Jr e Back-end Jr

Tenho conhecimentos em:
Node.js
Javascript
HTML
CSS
React js
PostgresQL
Desenvolvimento de API RestFul
Git e Github
Deploy Heroku, Netlify

LinkedIn: https://www.linkedin.com/mwlite/in/rodolfo-arauj0

Github: https://github.com/RodolfoArauj0

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
