### ISSUE TITLE
[REMOTO][Currais Novos/RN] Aryan Dantas Gomes

### ISSUE THREAD

**Issue by aryangomes** [backend-br/me-contrata#95]
## Nome completo

Aryan Dantas Gomes

## Localidade

Currais Novos/RN

## Apresentação

Olá eu sou Aryan, sou técnologo em Sistemas para Internet pelo IFRN e tenho conhecimento em PHP e Laravel.

Sou um curioso da área de tecnologia. Gosto de conhecer as novidades tecnológicas e dos benefícios que elas trazem para a sociedade. Acho interessante ferramentas que automatizam procedimentos repetidos. Além disso, gosto de expandir eu conhecimento em geral, pois acredito que isso pode melhorar a vida de forma geral. Meus pontos fortes são o planejamento e a execução de atividades.

## Outras Informações

Tenho interesse em trabalhar remotamente e não tenho disponibilidade em me mudar.

## Especialidades

- PHP
- Laravel
- SQL
- HTML
- CSS
- Javascript
- Git
- Docker

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

[Linkedin](https://www.linkedin.com/in/aryangomes/)

## Site

[Github](https://github.com/aryangomes)

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
