### ISSUE TITLE
[Serra/ES] Vinícius Apolinario Melo

### ISSUE THREAD

**Issue by Vinicius-AMelo** [backend-br/me-contrata#96]
## Nome completo

Vinícius Apolinário Melo

## Localidade

Serra/Espírito Santo

## Apresentação

Desenvolvedor FullStack

## Outras Informações

Disponibilidade absoluta

## Especialidades

- JavaScript
- TypeScript
- SASS
- React
- Next.JS
- Redux
- Node.Js
- Express
- MySQL
- MongoDB

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/vin%C3%ADcius-melo-59831522a/

## Site

https://github.com/Vinicius-AMelo
https://vinicius-amelo.github.io/portifolio-react/

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
