### ISSUE TITLE
[Apucarana/PR] Cassid Horimi

### ISSUE THREAD

**Issue by Cassidhorimi** [backend-br/me-contrata#97]
## Nome completo

Cassid Hajimi Horimi

## Localidade

Apucarana/PR

## Apresentação

Sou um apaixonado por tecnologia desde criança quando ganhei meu primeiro computador e quando tive meu primeiro contato com programação soube que um dia eu iria ingressar nessa área. Busco sempre o desenvolvimento pessoal e de pessoas ao meu redor.
Em setembro de 2021 comecei minha jornada na área de programação e ingressei no curso de Desenvolvimento Web Fullstack na Trybe, atualmente estou terminando módulo de Back end.

## Outras Informações

Preferência para vagas back-end
Disponível das 08:00 as 18:00

## Especialidades

- JavaScript
- TypeScript
- ReactJs
- NodeJs
- Express
- Sequelize
- Mongoose
- Testes unitarios (Mocha, Jest, Chai)
- MySQL
- MongoDB
- HTML
- CSS
- SOLID
- POO
- SCRUM
- KANBAN

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://linkedin.com/in/cassidhorimi

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
