### ISSUE TITLE
[São Paulo/SP] Caio Oliveira

### ISSUE THREAD

**Issue by ocaio275** [backend-br/me-contrata#98]
## Nome completo

Olá, me chamo Caio Silva Oliveira dos Santos

## Localidade

Atualmente estou localizado na cidade de São Paulo, resido na zona leste

## Apresentação

Tenho 24 anos, sou completamente apaixonado por tecnologia, sou Analista de desenvolvimento PL e estou me aprimorando em Back-End

E atualmente estou me especializando em Node.Js, MongoDB e AWS
## Outras Informações

Estou estudando Node.JS, AWS e MongoDB pela plataforma Udemy

## Especialidades

- JavaScript
- HTML
- CSS
- PHP
- MySQL
- MongoDB
- Express
- AWS

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/caio-oliveira-746188153/

## Site

Em desenvolvimento

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
