### ISSUE TITLE
[João Monlevade/MG] Gabriel Antônio

### ISSUE THREAD

**Issue by gabriel-abn** [backend-br/me-contrata#99]
## Nome completo

Gabriel Antônio Batista Nascimento

## Localidade

João Monlevade - Minas Gerais

## Apresentação

Meu nome é Gabriel Antônio, sou graduando no sétimo período do curso de Sistemas de Informação pela Universidade Federal de Ouro Preto - Campus João Monlevade, e desde a minha entrada na faculdade, me interesso muito pela área de desenvolvimento de software.

Não dependendo apenas dos estudos dentro da faculdade, me esforço e dedico para aprender por fora as tecnologias em alta no mercado de trabalho fazendo projetos pessoais que venham a agregar no meu conhecimento.

Tenho grande facilidade de aprender novas tecnologias e sou apaixonado por programação. Visto isso, estou a procura de uma oportunidade no mercado de trabalho na área de desenvolvimento de software, para agregar não só a mim, mas à empresa a qual estarei me dedicando e esforçando com objetivo principal da evolução de todos.

## Outras Informações

**Soft skills:**

- Proatividade
- Comunicação
- Trabalho em grupo
- Adaptabilidade

## Especialidades

- Programação em **Typescript** e **Javascript**
- Programação em ambiente **NodeJS**
- Algoritmos e estrutura de dados em **C**
- Conhecimentos em **C#** e **Python**
- **HTML/CSS**
- Conhecimentos em scripts **SQL**
- Versionamento de código com **Git**
- Manipulação de containers em **Docker**
- Conhecimento em comandos **Linux**
- Banco de dados **MySQL** e **PostgreSQL**

**Outras Hard skills:**
- Conhecimentos básicos em **Microsserviços**
- Desenvolvimento de código seguindo a **Clean Architecture**
- Conhecimentos de **DDD**
- Desenvolvimento de testes unitários seguindo as práticas **TDD**

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

LinkedIn: https://www.linkedin.com/in/gabriel-batista-868b7a180/

Email para contato: [gabriel.ab.nascimento@gmail.com](mailto:gabriel.ab.nascimento@gmail.com)

**Comment by gustavofreze** [comment]
Esta candidatura foi fechada, pois encontra-se há um bom tempo sem novas interações.
